# Generated by Django 5.0.6 on 2024-07-11 12:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodyname', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('length', models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('youtubelink', models.CharField(max_length=100, null=True)),
                ('thumbnail', models.CharField(max_length=100, null=True)),
                ('bodypart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video', to='videos.bodypart')),
            ],
        ),
    ]
