# Generated by Django 5.0.6 on 2024-07-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='alarms/')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_option', models.BooleanField(default=False)),
                ('interval', models.IntegerField(default=10, null=True)),
                ('is_alarm', models.BooleanField(default=True)),
                ('is_volumn', models.BooleanField(default=True)),
            ],
        ),
    ]
