# Generated by Django 5.0.7 on 2024-07-11 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0002_initial'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='is_option',
        ),
        migrations.AddField(
            model_name='alarmcontent',
            name='bodypart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarm_content', to='videos.bodypart'),
        ),
        migrations.AddField(
            model_name='option',
            name='fcm_token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='interval',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='option',
            name='is_alarm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='option',
            name='is_volumn',
            field=models.BooleanField(default=False),
        ),
    ]
