# Generated by Django 5.0.7 on 2024-07-11 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0003_remove_option_is_option_alarmcontent_bodypart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='last_push_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 15, 13, 14, 994405, tzinfo=datetime.timezone.utc)),
        ),
    ]
